### ISSUE TITLE
CSS Foundation

### ISSUE THREAD

**Issue by mcleanGit** [michaelpalumbo/apiapi#13]
Objective: place Foundation CSS hrefs into index.html and begin CSS styling using Foundation resources.  Issue: I added the requisite Foundation CSS hrefs to the index.html, creating a distinct index1.html for the purpose as a test so as not to screw up the current html, and pushed it to the develop branch. You can find it there. Problem is that the previously semi-functional html we looked at yesterday does NOT function with these additions. Goal was to get Foundation working as our CSS. The compressed foundation css cdn link is functional. Also the requisite additional cdn (Michael, could this be creating conflicts with existing JS?). I am trying to get to some CSS styling going for our site/app.

**Comment by michaelpalumbo** [comment]
> Problem is that the previously semi-functional html we looked at yesterday does NOT function with these additions

Hi Don, you need to explain what specifically is wrong, or at least what behaviour you're noticing that is off. Please also copy and paste what the browser console is reporting. Otherwise we won't know how to help/focus on. Thanks!

**Comment by michaelpalumbo** [comment]
Hi @mcleanGit 

Here's what I found...

the jquery cdn was commented out. We need this. Added back in. 

~/js/vendor/modernizr.js doesn't exist... added the cdn link.

~css/app.css doesn't exist. added it in /assets/css/

**Comment by mcleanGit** [comment]
Hi, Michael and Cincos: I've managed to delete this twice now in overloading info.
To answer only the diff in browser behaviour between index.html and test variant index1.html, see screenshots:
![index-html-startup](https://user-images.githubusercontent.com/94858165/152836075-334d7350-df58-4e6c-b793-dbbcd5fa230c.png)
![index-html-signed-in](https://user-images.githubusercontent.com/94858165/152836128-056c7008-db34-417a-b606-d1d835dd1b07.png)
![index-html-chord-return](https://user-images.githubusercontent.com/94858165/152836146-c755a736-b5fc-4462-9be4-76937a4c1870.png)
And
![index1-html-startup](https://user-images.githubusercontent.com/94858165/152836188-91d25bd4-d40b-4187-82d3-d5f6de6d4f32.png)
![index1-html-signed-in](https://user-images.githubusercontent.com/94858165/152836231-c50dc117-7237-412f-b09c-f4efd3d0dd81.png)
![index1-html-chord-return](https://user-images.githubusercontent.com/94858165/152836242-09e800d7-04ca-4d01-9b26-7c852611cc72.png)
Not too serious now that Michael uncommented the jquery cdn (was experimenting with removing various items).
In my first reaction, the chord calls stopped happening altogether.
**The larger issue is that we need to get Foundation CSS operational and accelerate our styling efforts.**
More on that later today.  But I need to mobilize several of us on this.
Will address other concerns separately in Trello and or Issues.
