### ISSUE TITLE
Problem with the proxy, cannot fetch

### ISSUE THREAD

**Issue by michaelpalumbo** [michaelpalumbo/apiapi#14]
```VM222:1 GET https://chriscastle.com/proxy/hooktheory.php?cp=1&bearer=a15b4d3e14bff0d909d72674d0d0a35a&nodes net::ERR_CERT_DATE_INVALID```

I can confirm this only began this evening (was working as of yesterday afternoon). This problem is reproduced on my local version of the app, as well as the one served at https://michaelpalumbo.github.io/apiapi

I've messaged Chris about this.

**Comment by wctestbank** [comment]
If nothing else changed, I guess the proxy somehow broke? Guess you just have to wait for Chris to look at it from his side.

**Comment by michaelpalumbo** [comment]
> If nothing else changed, I guess the proxy somehow broke? Guess you just have to wait for Chris to look at it from his side.

Yep. Although there's still tickets from the trello we can work on. I just fixed the chordnaming problem by isolating the development to a codepen.io project :) -- speaking of which there's new changes to develop if you'd like to pull. Let me know if you want any help with codepen

**Comment by michaelpalumbo** [comment]
Good news: it'll be back up in 5 minutes. Chris said that the SSL certificate for his site expired, and it only expires annually. What timing!
