### ISSUE TITLE
experiments with the api explorer idea

### ISSUE THREAD

**Issue by michaelpalumbo** [michaelpalumbo/apiapi#2]
hi everyone, I experimented a bit with the api explorer idea I had. 

It's live at https://michaelpalumbo.github.io/apiapi/apiFinder/ 

and the code is in the /apiFinder in this repo. As a first pass it was actually pretty reasonable to get the list of categories, populate a menu with them, then return all entries matching that category as html in the page.

**Comment by mcleanGit** [comment]
Yes.  Works well. Not sure I follow the last steps of this. (A bit slow.) Will try it out with your code tonight. I note that repeating the search with another category from the pull-down menu (without closing) concatenates the list.  Art&Design, + Videos, +Finance, etc.

**Comment by michaelpalumbo** [comment]
> I note that repeating the search with another category from the pull-down menu (without closing) concatenates the list. Art&Design, + Videos, +Finance, etc.

Ah thanks for catching that @mcleanGit ... and fixed. I added 

```javascript
    $('.container').empty()
```

to the beginning of the list population function to clear the previous results each time you select a category.

**Comment by michaelpalumbo** [comment]
> Not sure I follow the last steps of this.
@mcleanGit sure. I'll document my code now to help you out when you take a look at it later!

**Comment by mcleanGit** [comment]
Got it. Thanks.


Don McLean
Professor of Musicology and
Music Theory
Faculty of Music
University of Toronto
Edward Johnson Building
80 Queen's Park Cr.
Toronto, ON, Canada
M5S 2C5
T: 647-921-3761
E: ***@***.***
W: www.music.utoronto.ca

On Jan 31, 2022, at 17:00, Michael Palumbo ***@***.***> wrote:

﻿
You don't often get email from ***@***.*** Learn why this is important<http://aka.ms/LearnAboutSenderIdentification>

Not sure I follow the last steps of this.
@mcleanGit<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FmcleanGit&data=04%7C01%7Cmclean%40utoronto.ca%7Cdeced81a54d54821db6008d9e5050efd%7C78aac2262f034b4d9037b46d56c55210%7C0%7C0%7C637792632149887043%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WkgmR6T9Dk%2FaXqk1I05BCHEmv5EgO2DLc1XlpHY2UuQ%3D&reserved=0> sure. I'll document my code now to help you out when you take a look at it later!

—
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmichaelpalumbo%2Fapiapi%2Fissues%2F2%23issuecomment-1026253987&data=04%7C01%7Cmclean%40utoronto.ca%7Cdeced81a54d54821db6008d9e5050efd%7C78aac2262f034b4d9037b46d56c55210%7C0%7C0%7C637792632149887043%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pOQF3zyi7i7WoUn3orJEEO1PNu3ljtvTBRatnA89w20%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWTWXNILOR6WBUF4ZL2HCPLUY4A63ANCNFSM5NHOLIDQ&data=04%7C01%7Cmclean%40utoronto.ca%7Cdeced81a54d54821db6008d9e5050efd%7C78aac2262f034b4d9037b46d56c55210%7C0%7C0%7C637792632149887043%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OkNw5PnRm6g3gaOO7Qnw1QMpr26%2FrGIAYvRE5Ynl8ZE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmclean%40utoronto.ca%7Cdeced81a54d54821db6008d9e5050efd%7C78aac2262f034b4d9037b46d56c55210%7C0%7C0%7C637792632149887043%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VA2QL9sj8IhA0udGOsmtIBZA%2FGprTgSplqk0TbPsU3M%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cmclean%40utoronto.ca%7Cdeced81a54d54821db6008d9e5050efd%7C78aac2262f034b4d9037b46d56c55210%7C0%7C0%7C637792632149887043%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=o8sG%2Bs7XbCYBYfNMC0eKTD%2B%2BoGb2PmKpfn1sOXC8vFc%3D&reserved=0>.
