### ISSUE TITLE
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.

### ISSUE THREAD

**Issue by wctestbank** [michaelpalumbo/apiapi#20]
Receiving this error in the console on the github pages version of the site but it works fine locally.
![image](https://user-images.githubusercontent.com/95963915/153082717-10670a4b-a048-4efe-821d-473f54e9fa76.png)

**Comment by michaelpalumbo** [comment]
@wctestbank So the reason it works locally for you vs seeing this error on the live pages site is that the pages site runs from main, and the only way to get code into main is through a pull request, which you didn't do. 

From looking into it, it appears its a github pages-specific thing, and shouldn't affect the operation of our site. see 
https://github.blog/changelog/2021-04-27-github-pages-permissions-policy-interest-cohort-header-added-to-all-pages-sites/
https://github.community/t/i-have-no-idea-what-the-interest-cohort-is/179780/10

**Comment by wctestbank** [comment]
Ok, guess I'll close this issue
