### ISSUE TITLE
finding an api to report number of chords a song has

### ISSUE THREAD

**Issue by michaelpalumbo** [michaelpalumbo/apiapi#3]
I'm going to document my progress in nailing this problem

**Comment by michaelpalumbo** [comment]
https://api.uberchord.com/#songs seems promising

**Comment by michaelpalumbo** [comment]
https://api.uberchord.com/v1/chords/F_maj7 for example, returns: 

```json

[
  {
    "strings": "1 X 2 2 1 0",
    "fingering": "1 X 3 4 2 X",
    "chordName": "F,maj,7,",
    "enharmonicChordName": "F,maj,7,",
    "voicingID": "9223372036855892961",
    "tones": "F,A,C,E"
  }
]
```

**Comment by michaelpalumbo** [comment]
also of interest https://www.scales-chords.com/api/

**Comment by michaelpalumbo** [comment]
I went on a DEEEEP dive (its 10:30pm and i've been searching for chord apis since our meeting ended, and I've come up with many dead ends. Here's what i'm going to try next:

Using this tutorial about oauth2 w/ fetch https://gomakethings.com/using-oauth-with-fetch-in-vanilla-js/

I'll try and authenticate a session with the music theory api hooktheory https://www.hooktheory.com/api/trends/docs#authentication

To return songs containing a given chord progression. While this isn't exactly "filter by number of chords" and is instead, "filter by progression", its a start, and the closest to satisfying the project idea i've come across so far. https://www.hooktheory.com/api/trends/docs#songs

**Comment by mcleanGit** [comment]
Hi, Michael. Thanks for this. Yes, I'm unfortunately not surprised. I suppose if we could get a progression list, we could find a way to count the chords (remove duplications). But I'm not optimistic. One thought was, could we partner with an api to add such information based on the readily available but informal tutorial YouTube etc stuff out there. There you find the chords and the songs, and usually the tablature. The such info might be tipped into an existing api as a valuable add-on. But such a thing is probably outside the scope of the possible within the timeframe.

**Comment by mcleanGit** [comment]
https://www.amitkohli.com/chord-progressions-of-5-000-songs/
Left this one in Slack too. Same guys. 
https://github.com/DataStrategist/Musical-chord-progressions
Here's his github repo.

**Comment by michaelpalumbo** [comment]
> Hi, Michael. Thanks for this. Yes, I'm unfortunately not surprised. I suppose if we could get a progression list, we could find a way to count the chords (remove duplications). But I'm not optimistic. 

Yeah. I think maybe we could shift from _finding songs based on # of chords_, to _songs based on progressions_, since that is what the uberchord api permits. I'm going to document experiments with this idea in issue #4.

> One thought was, could we partner with an api to add such information based on the readily available but informal tutorial YouTube etc stuff out there. There you find the chords and the songs, and usually the tablature. The such info might be tipped into an existing api as a valuable add-on. But such a thing is probably outside the scope of the possible within the timeframe.

Yes I think this is a good idea but I also share the concern that it's outside the scope. We only have one week to make this webapp.
